version: '3.4'
services:
  db:
    container_name: project_nokasoft_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'project_nokasoft_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./docker/db:/var/lib/mysql
  app:
    container_name: project_nokasoft_laravel
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 'project_nokasoft_laravel'
    ports:
      - 8000:8000
    # command: sh docker/docker-entrypoint.sh
    volumes:
      - ./:/var/www/html